import { StyleSheet } from 'react-native';

import { COLORS, FONTS } from 'src/constants';
import { hp, sp, wp } from 'src/utils';

export const styles = StyleSheet.create({
  resultsOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 500,
  },

  exitOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },

  closeOverlayBtn: {
    position: 'absolute',
    top: hp(60),
    right: wp(30),
    width: wp(40),
    height: wp(40),
    borderRadius: wp(20),
    backgroundColor: COLORS.purple_overlay_dark,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 501,
  },
  closeOverlayText: {
    fontSize: sp(20),
    fontFamily: FONTS.semiBold,
    color: COLORS.white,
  },

  rulesContent: {
    width: '100%',
    alignItems: 'center',
    gap: hp(20),
    paddingTop: hp(66),
  },
  rulesImagesRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginBottom: hp(10),
  },
  rulesImageContainer: {
    alignItems: 'center',
  },
  rulesCarImage: {
    width: wp(120),
    height: hp(100),
  },
  rulesFishImage: {
    width: wp(100),
    height: hp(80),
  },
  plusOneText: {
    fontSize: sp(24),
    fontFamily: FONTS.extraBold,
    color: COLORS.orange,
    textShadowColor: COLORS.correct_answer,
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
    marginBottom: hp(5),
  },
  minusOneText: {
    fontSize: sp(24),
    fontFamily: FONTS.extraBold,
    color: COLORS.wrong_answer,
    textShadowColor: COLORS.orange,
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
    marginBottom: hp(5),
  },
  rulesTextContainer: {
    width: '88%',
    padding: wp(10),
    alignItems: 'center',
    backgroundColor: COLORS.purple,
    borderWidth: 1,
    borderColor: COLORS.white_overlay_light,
    borderRadius: wp(16),
  },
  rulesDescription: {
    fontSize: sp(12),
    textAlign: 'center',
  },
  rulesHighlight: {
    fontSize: sp(15),
    fontFamily: FONTS.semiBold,
    textAlign: 'center',
    marginTop: hp(10),
  },
  playButton: {
    width: '66%',
    alignSelf: 'center',
    marginTop: hp(20),
    borderRadius: wp(16),
    borderWidth: 1,
    borderColor: COLORS.white_overlay_light,
    backgroundColor: COLORS.purple_overlay_medium,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(14),
    paddingHorizontal: wp(50),
    gap: wp(10),
  },
  playButtonOverlay: {
    position: 'absolute',
    top: wp(4),
    left: wp(4),
    right: wp(4),
    bottom: wp(4),
    backgroundColor: COLORS.purple_overlay_light,
    borderRadius: wp(12),
  },
  playButtonText: {
    fontSize: sp(18),
  },
  playIcon: {
    width: wp(24),
    height: wp(24),
  },
  timerContainer: {
    position: 'absolute',
    top: hp(10),
    right: wp(10),
    alignItems: 'flex-end',
    zIndex: 50,
  },
  timerBadge: {
    backgroundColor: COLORS.purple_overlay_dark,
    borderRadius: wp(12),
    paddingVertical: hp(6),
    paddingHorizontal: wp(14),
    marginBottom: hp(5),
    borderWidth: 1,
    borderColor: COLORS.purple_border,
  },
  timerText: {
    fontSize: sp(18),
    fontFamily: FONTS.semiBold,
  },
  scoreBadge: {
    backgroundColor: COLORS.purple_overlay_dark,
    borderRadius: wp(12),
    paddingVertical: hp(8),
    paddingHorizontal: wp(18),
    borderWidth: 1,
    borderColor: COLORS.purple_border,
    minWidth: wp(50),
    alignItems: 'center',
  },
  scoreText: {
    fontSize: sp(20),
    fontFamily: FONTS.extraBold,
  },
  spawnedItem: {
    position: 'absolute',
    zIndex: 10,
  },
  biggyImage: {
    width: wp(100),
    height: hp(80),
  },
  fishImage: {
    width: wp(80),
    height: hp(60),
  },
  floatingScore: {
    position: 'absolute',
    zIndex: 20,
  },
  floatingScoreText: {
    fontSize: sp(28),
    fontFamily: FONTS.extraBold,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  positiveScore: {
    color: COLORS.correct_answer,
  },
  negativeScore: {
    color: COLORS.wrong_answer,
  },
  resultsContainer: {
    padding: wp(20),
    width: '75%',
    alignItems: 'center',
    gap: hp(8),
  },
  resultsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.purple_overlay_medium,
    borderRadius: wp(10),
    paddingVertical: hp(8),
    paddingHorizontal: wp(15),
    width: '100%',
  },
  resultsValueBadge: {
    backgroundColor: COLORS.purple_overlay_dark,
    borderRadius: wp(8),
    paddingVertical: hp(6),
    paddingHorizontal: wp(16),
    minWidth: wp(50),
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.purple_border,
  },
  resultsValue: {
    fontSize: sp(16),
    fontFamily: FONTS.semiBold,
  },
  resultsCarIcon: {
    width: wp(70),
    height: hp(45),
  },
  resultsFishIcon: {
    width: wp(55),
    height: hp(35),
  },
  finalResultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.purple_overlay_medium,
    borderRadius: wp(10),
    paddingVertical: hp(10),
    paddingHorizontal: wp(15),
    width: '100%',
  },
  finalResultLabel: {
    fontSize: sp(14),
    fontFamily: FONTS.medium,
  },
  finalScoreBadge: {
    backgroundColor: COLORS.purple,
    borderRadius: wp(8),
    paddingVertical: hp(6),
    paddingHorizontal: wp(16),
    minWidth: wp(50),
    alignItems: 'center',
  },
  finalScoreText: {
    fontSize: sp(16),
    fontFamily: FONTS.extraBold,
  },
  startAgainButton: {
    marginTop: hp(8),
    paddingVertical: hp(12),
    width: '100%',
  },
  startAgainText: {
    fontSize: sp(15),
    fontFamily: FONTS.semiBold,
  },
  exitModalContainer: {
    padding: wp(24),
    width: '80%',
    alignItems: 'center',
    gap: hp(12),
  },
  exitTitle: {
    fontSize: sp(20),
    fontFamily: FONTS.extraBold,
    textAlign: 'center',
  },
  exitSubtitle: {
    fontSize: sp(14),
    fontFamily: FONTS.regular,
    textAlign: 'center',
    opacity: 0.9,
    marginBottom: hp(8),
  },
  exitButtonsRow: {
    flexDirection: 'row',
    gap: wp(12),
    width: '100%',
  },
  exitStayButton: {
    flex: 1,
    paddingVertical: hp(12),
    backgroundColor: COLORS.light_purple_bckd,
  },
  exitExitButton: {
    flex: 1,
    paddingVertical: hp(12),
    backgroundColor: COLORS.wrong_answer,
  },
  exitButtonText: {
    fontSize: sp(15),
    fontFamily: FONTS.semiBold,
  },
});
